### ISSUE TITLE
Goal: allow customer to stream salary to their team

### ISSUE THREAD

**Issue by markholdex** [holdex/payment-streaming#1]
# Business requirements
We're are building a payment/salary streaming solution for our customers and partners. The customer should be able to stream USDT or USDC every second/block to a wallet address specified by their team member (payee). The payee receives their tokens by claiming them at any point they want. 

# [Whitepaper draft](https://docs.google.com/document/d/1JhCrm3TRPtEjnkYqgb0EOXBJ_ZPVLylF5c9VonioUFc/edit?usp=sharing)

```[tasklist]
### Problems
- [ ] https://github.com/holdex/payment-streaming/issues/2
```

**Comment by accompany1205** [comment]
@markholdex  I have some questions at time moment.
-What chain is it supposed to deploy?
-In this sentence "The payee receives their tokens by claiming them at any point they want."
Do you mean the tokens USDT or USDC or sth else?

**Comment by markholdex** [comment]
@accompany1205 

1) Chain, EVM compatible. We can decide later where to deploy. For testnet, pick from Polygon Mumbai or Ethereum Sepolia.
2) I meant USDT or USDC. Depending on what token the customer chose. (You can check the doc for more clarity, V1)

**Comment by markholdex** [comment]
Feel free to leave comments in the document where you have them.

**Comment by accompany1205** [comment]
@markholdex Will transactions(stream USDT/USDC) be triggered every second?
In this case, did you think about gas fee?

**Comment by markholdex** [comment]
@accompany1205 stream is different from transaction itself. Transactions don't have to happen every second. Transaction only happen when the streaming is created and claimed. The smart contract should be capable to calculate how much time has passed and include the rest of the parameters so that when the stream is claimed, it know how much to transfer to the payee.

**Comment by accompany1205** [comment]
@markholdex 
No problem for the requirements on the smart contract side.
Does Payer deposit stablecoins into streaming instance directly?
In this case, what do you mean by every second/block in the sentence below?
"The customer should be able to stream USDT or USDC every second/block to a wallet address specified by their team member (payee)."

**Comment by markholdex** [comment]
> "The customer should be able to stream USDT or USDC every second/block to a wallet address specified by their team member (payee)."

This is a business (non-technical) description of the requirements. Also from the business perspective, we should be able to see the how each second some USDC accrues. How it is technically implemented, is up to you as long as the business requirements are satisfied.

**Comment by accompany1205** [comment]
@markholdex 
A new contract will be deployed for each stream instance whenever manager create a new instance.
Manager contract will deposit stablecoins to the instance contract when it's deployed.(Payer should deposit enough funds for instances before creating them)
And each instance contract will be used dedicatedly for each payee and once it's expired or canceled, the instance won't be used anymore.
If Payer want to create a new instance again, a new  instance contract will be deployed again.

- Do you agree with the logic?
- Can two instances for the  same payee be existing at the same time?(Of course, the option a) and option b) will be different instance)

**Comment by accompany1205** [comment]
@markholdex Could you help me with answering questions?

**Comment by markholdex** [comment]
> @markholdex A new contract will be deployed for each stream instance whenever manager create a new instance. Manager contract will deposit stablecoins to the instance contract when it's deployed.(Payer should deposit enough funds for instances before creating them) And each instance contract will be used dedicatedly for each payee and once it's expired or canceled, the instance won't be used anymore. If Payer want to create a new instance again, a new instance contract will be deployed again.
> 
> * Do you agree with the logic?
> * Can two instances for the  same payee be existing at the same time?(Of course, the option a) and option b) will be different instance)

I can't define exactly the best smart contract architecture option. We would like to see what is your proposed solution in this case. I would recommend you to document your solution into Doc or here before you proceed to implementation. 

Looking at your current proposal, it looks logically good. The stream however can't expire by default (unless that is specified). There could be not enough funds, and the payer should be able to top-up the contract as it goes. There is no problem if two separate stream instances for the same payee would exists at this moment.

**Comment by accompany1205** [comment]
@markholdex 
The logic contains the best smart contract architecture and it's just a solution itself.
In case of linear vesting, an interval or end date should be specific for each one as described on the docs. So when creating a stream, it should have a param which determines whether it is option a) or option b)
a. Stream with an end date (linear vesting)
    i. With cliff (from 0 to N days)
b. Stream without an end date with a specified rate per month

**Comment by zolotokrylin** [comment]
@accompany1205 please start with this issue #4.

**Comment by CTAPCKPIM** [comment]
@zolotokrylin 
Can you tell me what is better and I should start, so that the process gets off the ground

**Comment by almon-s** [comment]
@markholdex what would be the ETA here? Will we be able to test before Monday? Thanks
