### ISSUE TITLE
Problem: not gas-efficient way of handling errors

### ISSUE THREAD

**Issue by zolotokrylin** [holdex/payment-streaming#19]
Starting from Solidity v0.8.4, there is a convenient and gas-efficient way to describe to users why an operation failed through the use of custom errors. The require statement uses strings to provide additional information about failures (e.g. require(blockings[user] == true, "non blocked user");), but they are rather expensive, especially when it comes to deploying cost, and it is difficult to use dynamic information in them. BVSS: AO:S/AC:L/AX:L/C:N/I:N/A:N/D:N/Y:N/R:N/S:U (0.0) Recommendation: It is recommended to implement custom errors instead of reverting strings. References: https://blog.soliditylang.org/2021/04/21/custom-errors/ 

_Originally posted by @zolotokrylin in https://github.com/holdex/payment-streaming/pull/15#discussion_r1251863530_

sub of https://github.com/holdex/payment-streaming/issues/2

**Comment by accompany1205** [comment]
All the `require` statements should be replaced with `revert`?

**Comment by markholdex** [comment]
@accompany1205 almost, but this is what I also understand from the documentation. We currently use `require` and then specify the error message. However, in the new version, `require` is not supported together with `revert`. It will require to refactor into `If else` functions. 
<img width="841" alt="image" src="https://github.com/holdex/payment-streaming/assets/46079535/92c0a89c-cb35-4daa-876f-8db3c2477964">

**Comment by accompany1205** [comment]
@markholdex  Okay, I will replace all of them.
