### ISSUE TITLE
Goal: develop MVP streaming contracts

### ISSUE THREAD

**Issue by markholdex** [holdex/payment-streaming#2]
```[tasklist]
### Problems
- [ ] https://github.com/holdex/payment-streaming/issues/4
- [ ] https://github.com/holdex/payment-streaming/issues/5
- [ ] https://github.com/holdex/payment-streaming/issues/6
- [ ] https://github.com/holdex/payment-streaming/issues/9
- [ ] https://github.com/holdex/payment-streaming/issues/8
- [ ] https://github.com/holdex/payment-streaming/issues/11
- [ ] https://github.com/holdex/payment-streaming/issues/12
- [ ] https://github.com/holdex/payment-streaming/issues/17
- [ ] https://github.com/holdex/payment-streaming/issues/19
- [ ] https://github.com/holdex/payment-streaming/issues/23
- [ ] https://github.com/holdex/payment-streaming/issues/25
- [ ] https://github.com/holdex/payment-streaming/issues/28
- [ ] https://github.com/holdex/payment-streaming/issues/29
- [ ] https://github.com/holdex/payment-streaming/issues/30
- [ ] https://github.com/holdex/payment-streaming/issues/34
- [ ] https://github.com/holdex/payment-streaming/issues/37
- [ ] https://github.com/holdex/payment-streaming/issues/36
- [ ] https://github.com/holdex/payment-streaming/issues/41
- [ ] https://github.com/holdex/payment-streaming/issues/43
- [ ] https://github.com/holdex/payment-streaming/issues/45
- [ ] https://github.com/holdex/payment-streaming/issues/21
- [ ] https://github.com/holdex/payment-streaming/issues/60
- [ ] https://github.com/holdex/payment-streaming/issues/61
- [ ] https://github.com/holdex/payment-streaming/issues/66
- [ ] https://github.com/holdex/payment-streaming/issues/69
- [ ] https://github.com/holdex/payment-streaming/issues/70
- [ ] https://github.com/holdex/payment-streaming/issues/79
- [ ] https://github.com/holdex/payment-streaming/issues/78
- [ ] https://github.com/holdex/payment-streaming/issues/80
```

**Comment by CTAPCKPIM** [comment]
@markholdex 
Questions:
1) We have two roles (for example):
     - USDC/T sender:
        a) Creation of a "flow" and transfer to the SC "USDC/T";
      
     - USDC/T receiver:
        a) You can always get USDC/T
        b) Is the USDC/T amount calculated using value*hours for each recipient personally?

2) Creating a project from scratch and writing the SC is completely on me?
3) Writing tests me after the final code is approved by you?

P.S. Later I will ask some important questions about future functions

**Comment by markholdex** [comment]
Hey @CTAPCKPIM,

You can also check some of the answers from the Goal conversation and the document attached in https://github.com/holdex/payment-streaming/issues/1

1) Yes, we do have 2 roles. One is the sender and other is the receiver. 
> b) Is the USDC/T amount calculated using value*hours for each recipient personally?
Yes, for each receiver is personally calculated. Because each receiver has it's own rate per hours or rate per month.

2) Yes, but make sure you coordinate with @accompany1205 because he also seem to start on it. There are no updates from him however, make sure you can split the work.  
3) Test is on you once we approve the functionality.

**Comment by CTAPCKPIM** [comment]
Hi @accompany1205
At what stage are you now, and what is ready? So that I understand where I should start so that we can work well together

**Comment by accompany1205** [comment]
@CTAPCKPIM I started just now, so I don't have any progress yet.
However, if you have questions, feel free to ask me.
I'm happy to discuss with you.

**Comment by CTAPCKPIM** [comment]
@accompany1205 
When the hardhat project will be created say me

So that I would know that I do not need to create it and install dependencies, as I understand it, you have already started doing this? Because I don't understand where to start my work

**Comment by accompany1205** [comment]
@markholdex , @CTAPCKPIM Actually, this project is not a bit picture for us.
I would like to build this project with own ideas so that we could show our experience and skills individually.
However, I'm happy to share my thoughts about this project with you(@CTAPCKPIM )

**Comment by CTAPCKPIM** [comment]
If @markholdex agrees, me too
@accompany1205 your variant is very interesting and I will be to sharing thoughts about this project

**Comment by markholdex** [comment]
@accompany1205 If you can also display leadership skills and be able to break down the smart contract problem into decoupled PRs that you can delegate to other team members, we are happy about that. But, If you don't want to do it, let us know. 
Either way, keep transparency of your work. Open and attach a draft PR and commit a few times a days so everyone could see your progress and plan accordingly.

**Comment by CTAPCKPIM** [comment]
@markholdex 
What should I do? Start doing work autonomously as @accompany1205 wrote above?

**Comment by markholdex** [comment]
@CTAPCKPIM, I'm waiting for @accompany1205 's response. Otherwise, by tomorrow, I'll have a different task for you.

**Comment by accompany1205** [comment]
@markholdex , @CTAPCKPIM ok sure, no problem

**Comment by accompany1205** [comment]
@CTAPCKPIM what is the best way to chat with you?
Do you use Telegram or Discord?
And Skype is also welcome.

**Comment by markholdex** [comment]
@CTAPCKPIM @accompany1205 Share your Telegram and I'll organize the channel for us.

**Comment by CTAPCKPIM** [comment]
@accompany1205 
Telegram: @NFYSBGFA

**Comment by accompany1205** [comment]
@markholdex , @accompany1205 
@speardevking

**Comment by zolotokrylin** [comment]
Problem: can't create stream

**Comment by zolotokrylin** [comment]
Problem: can't claim USDT from my stream

**Comment by zolotokrylin** [comment]
Problem: can't receive a commission on claimed payment

**Comment by zolotokrylin** [comment]
@markholdex great job for defining more problems so they guys can pick them up 👍 
Could you please: 
- refer to the goal in every sub-problems you create
- use the following terminology when we are talking about users: Payer, Payee, Admin. No "team members", "customers", etc. Let make sure we use the same naming everywhere

**Comment by zolotokrylin** [comment]
@CTAPCKPIM @accompany1205 this goal is assigned to you. You guys can take ownership here and push it forwards

**Comment by CTAPCKPIM** [comment]
@zolotokrylin / @markholdex 

Can I start writing tests?

**Comment by markholdex** [comment]
@accompany1205 what do you think? Can you define a simple Problem statement for @CTAPCKPIM to start working on?

**Comment by CTAPCKPIM** [comment]
@accompany1205
For local tests I will use mocked ERC20.sol (stablecoin)

**Comment by CTAPCKPIM** [comment]
@zolotokrylin / @markholdex 

What about `READMI.md`, what would it be a good and beautiful **description** of the project on GitHub? I can do it

**Comment by zolotokrylin** [comment]
@holdex/payment-streaming-team anything else is missing here? When are we closing this goal?

**Comment by almon-s** [comment]
@zolotokrylin once the smart contract coverage is at a 100% we should be able to close this goal

**Comment by markholdex** [comment]
@accompany1205 do we need a final redeployment here after the latest changes? So we can test things out?

**Comment by accompany1205** [comment]
@markholdex Yes, ofc.

**Comment by almon-s** [comment]
@accompany1205 when can we get that done by?

**Comment by markholdex** [comment]
@almon-s done
