### ISSUE TITLE
Problem: Payee can claim USDT even if his stream was terminated during cliff period

### ISSUE THREAD

**Issue by zolotokrylin** [holdex/payment-streaming#21]
Because the stream termination period + termination date is bigger than cliff period, the stream will accumulate amount for the  remaining time. Payee shouldn't be able to claim USDT if his stream was terminated before cliff period end. 

sub of #2

**Comment by markholdex** [comment]
@accompany1205 I believe we can close this one. Because Payer can terminate stream at any time.

**Comment by accompany1205** [comment]
Yeah, I think so

**Comment by zolotokrylin** [comment]
@markholdex , can Payer stop the stream immediately within the cliff period without waiting for the termination period to elapse? If not, then this issue can't closed as it is not resolved.

**Comment by markholdex** [comment]
@zolotokrylin terminate function is not followed by any verification related to cliff. So yes, it can be stopped within the cliff period.

**Comment by zolotokrylin** [comment]
@markholdex Are you sure? 
I can't see it in contracts code

**Comment by markholdex** [comment]
@zolotokrylin sure. Here is the termination function. It doesn't have any modifier for verification related to cliff 

https://github.com/holdex/payment-streaming/blob/edc051ceec4827d0784366219cc2102fbf30b852/contracts/StreamManager.sol#L179

**Comment by zolotokrylin** [comment]
@markholdex 
https://github.com/holdex/payment-streaming/blob/edc051ceec4827d0784366219cc2102fbf30b852/contracts/StreamManager.sol#L151

The way I read it, if Payer terminate agreement within cliff he will need to still pay for the Termination Period, but this is wrong.

**Comment by markholdex** [comment]
@zolotokrylin now I understood what you meant. I will modify the problem statement to reflect that.

**Comment by markholdex** [comment]
@accompany1205 please have a look at this Problem. Thanks!

**Comment by zolotokrylin** [comment]
Are the tests written for this use case?
