### ISSUE TITLE
Problem: Function "setClaimable();" can call all

### ISSUE THREAD

**Issue by CTAPCKPIM** [holdex/payment-streaming#28]

**Comment by accompany1205** [comment]
The issue is already solved.
The setClaimable() function is declared as private and  is called in cancelOpenStream() function. Only payer can call cancelOpenStream() function. So Anyone except payer can't call the function.

Maybe I am wrong.
@CTAPCKPIM @markholdex Can you check it again?

**Comment by CTAPCKPIM** [comment]
@accompany1205 

I just looked, and we have the same function in the contracts "OpenStream.sol" and "StreamManager.sol" that essentially does the same thing

1) https://github.com/holdex/payment-streaming/blob/fix-issue29/contracts/OpenStream.sol#102-104
2) https://github.com/holdex/payment-streaming/blob/fix-issue29/contracts/StreamManager.sol#95-97

As I understand it, you rewrote/supplemented the code on your part

**Comment by CTAPCKPIM** [comment]
@markholdex / @accompany1205  
I created this problem because the function `setClaimable(bool);` what's in `OpenStream.sol` can be called by anyone, and I don't think it's good for future users

P.S. If I'm wrong then correct me

**Comment by accompany1205** [comment]
@CTAPCKPIM We don't need "OpenStres.sol" at the moment. All the logic is implemented in "StreamManager.sol"

**Comment by CTAPCKPIM** [comment]
> @CTAPCKPIM We don't need "OpenStres.sol" at the moment. All the logic is implemented in "StreamManager.sol"
@accompany1205 
I understand that at the moment it does not matter, but it will need to be decided anyway

**Comment by markholdex** [comment]
Not planned because the function will be removed in #34
