### ISSUE TITLE
Problem: can't create open stream with USDT

### ISSUE THREAD

**Issue by zolotokrylin** [holdex/payment-streaming#4]
Payer can't create an open stream with USDT

ACs: 
- [ ] specify Payee wallet address
- [ ] specify Payee monthly rate (30 days)

"Open" means there is not specified termination of the stream; it just streams

_Originally posted by @zolotokrylin in https://github.com/holdex/payment-streaming/issues/2#issuecomment-1612571558_

**Comment by zolotokrylin** [comment]
@accompany1205 Start with this problem. Don't overthink ahead.
Create PR to solve exactly this problem and nothing more. When you create PR, provide ETA. Thanks!

**Comment by zolotokrylin** [comment]
- At least every 4 hours we expect to commit in that PR (better to commit more often). 
- Within a day we expect a merge that PR.

Based on that principles, commit something which can be done within a day (take into account the code review and all the questions you might have). Bite small peaces. Merge often and small PRs.

**Comment by accompany1205** [comment]
@zolotokrylin , @markholdex what do you mean this sentence?
"Payer can't create an open stream with USDT"

**Comment by markholdex** [comment]
This is the problem statement. This is how we collaborate as established in [Our Principles](https://holdex.io/c/learn/principles) and our [Guidelines](https://holdex.io/c/learn/github-strategy).

As engineer, you must resolve the problem statement. (mentioned earlier in the https://github.com/holdex/payment-streaming/issues/4#issuecomment-1612593867)

**Comment by accompany1205** [comment]
@zolotokrylin I accepted your github invitation, but I can't push commits directly.
Could you help me with that?
