### ISSUE TITLE
Problem: "claim" function has no test cases

### ISSUE THREAD

**Issue by accompany1205** [holdex/payment-streaming#47]
sub of #2 
It can be proceeded after #45

**Comment by accompany1205** [comment]
@CTAPCKPIM What issue are you working on?
Issue #47 or #50?

**Comment by accompany1205** [comment]
If you haven't stared yet, let me start.

**Comment by CTAPCKPIM** [comment]
@accompany1205 
Please tell me with `approve();`, I have already tried a lot and I can’t understand how and to whom exactly you need to give permission for the `claim();` function to work, I will be grateful for your help

**Comment by accompany1205** [comment]
What do you mean by approve()?

**Comment by CTAPCKPIM** [comment]
The function has two transferFrom(); which transfer tokens from the contract, and a commission, and for these lines the test shows that an approval is needed, I tried everything, but I have not yet found what exactly needs to be approved and in what sequence

**Comment by CTAPCKPIM** [comment]
Test:
![image](https://github.com/holdex/payment-streaming/assets/83241890/0896056d-ac79-4719-ae42-959fa6d2a7e5)

Error:
![image](https://github.com/holdex/payment-streaming/assets/83241890/9da93229-14e2-428e-b25a-e516bf5a2808)

**Comment by CTAPCKPIM** [comment]
Interesting to hear your guesses
I would just change `safeTransferFrom();` to `safeTransfer();`

**Comment by accompany1205** [comment]
@CTAPCKPIM Let me check

**Comment by accompany1205** [comment]
You can use approve() function.
Still not working?

**Comment by CTAPCKPIM** [comment]
I used it for different addresses and even wrote down the approve in the contract, but it didn’t help

**Comment by accompany1205** [comment]
@CTAPCKPIM Let me fetch it and try on my end.

**Comment by accompany1205** [comment]
@CTAPCKPIM I found issues

**Comment by CTAPCKPIM** [comment]
@accompany1205 
> @CTAPCKPIM I found issues

What was she in?

> @CTAPCKPIM Let me fetch it and try on my end.

No problem, I will only be grateful, and in the future too

**Comment by accompany1205** [comment]
@CTAPCKPIM Everything's fixed

**Comment by CTAPCKPIM** [comment]
@accompany1205  
Thanks! What was the problem? Would like to know to understand

**Comment by zolotokrylin** [comment]
PR is not merged yet
