### ISSUE TITLE
Problem: "terminate" has no test cases

### ISSUE THREAD

**Issue by accompany1205** [holdex/payment-streaming#48]
sub of #2 
It can be proceeded after #45

**Comment by accompany1205** [comment]
@CTAPCKPIM @markholdex Let me do this ticket.

**Comment by CTAPCKPIM** [comment]
@accompany1205 
No problem

**Comment by zolotokrylin** [comment]
@accompany1205 what's the PR here?

**Comment by accompany1205** [comment]
@zolotokrylin #55
