### ISSUE TITLE
Problem: can't claim USDT from my stream

### ISSUE THREAD

**Issue by zolotokrylin** [holdex/payment-streaming#5]
As Payee, I can't claim USDT from my streem

_Originally posted by @zolotokrylin in https://github.com/holdex/payment-streaming/issues/2#issuecomment-1612574913_

**Comment by markholdex** [comment]
@accompany1205 don't forget to follow our process: https://github.com/holdex/payment-streaming/issues/4#issuecomment-1612618658
Thanks!
