### ISSUE TITLE
Problem: "accumulation()" function has no test cases 

### ISSUE THREAD

**Issue by accompany1205** [holdex/payment-streaming#50]
Sub of #2
It can be proceeded after #45

**Comment by accompany1205** [comment]
@CTAPCKPIM Hey, what issues are you working on? If you haven't adhered any issue yet, please let me know. I will help you.

**Comment by CTAPCKPIM** [comment]
@accompany1205 
Hi), now I am writing a test for the `accumulation();` function, I ran into a problem that the accumulated value differs from the calculated value in the test

![image](https://github.com/holdex/payment-streaming/assets/83241890/fcf4bb90-63f9-4c05-83d0-5354b6c89b93)

![image](https://github.com/holdex/payment-streaming/assets/83241890/7c1d93fb-206b-4cc0-9690-9988fa594247)

Are there options for what's wrong?

**Comment by accompany1205** [comment]
@CTAPCKPIM It should be checked, let's say expect(....).to.equal(amount)
Does it make sense?

**Comment by accompany1205** [comment]
@CTAPCKPIM What issues are you working on and what is left?

**Comment by CTAPCKPIM** [comment]
@accompany1205 
> It should be checked, let's say expect(....).to.equal(amount)
Does it make sense?

Yes, I check through "expect(....).to.equal(amount)", but the bottom line is that the numbers that I compare do not converge
> What issues are you working on and what is left?

As soon as this problem is solved, I will quickly finish the rest of the tests for this function.

**Comment by accompany1205** [comment]
No issues left?

**Comment by CTAPCKPIM** [comment]
The question just remained, I don’t understand how to properly test the function call in order to compare its values, if you have thoughts on how to help me, I will be very happy

I'm sure the problem is in lines 194,195

**Comment by accompany1205** [comment]
Sure

**Comment by CTAPCKPIM** [comment]
@accompany1205 
Done, please take a look
https://github.com/holdex/payment-streaming/pull/54
