### ISSUE TITLE
Problem: accumulation() function doesn't work

### ISSUE THREAD

**Issue by markholdex** [holdex/payment-streaming#60]
accumulation() function is a view type of function. View type of functions can't be called by `msg.sender`. Implementation needs to be changed.

**Comment by zolotokrylin** [comment]
@markholdex what do you mean it can't be called?

**Comment by markholdex** [comment]
When calling a view function, there is no interaction within smart contract that will require a signature in the background. Therefore, by default, msg.sender is not passed. There are workarounds on internet on how to pass it and also depends on the libraries used. So, not to overcomplicate, easier to change.
