### ISSUE TITLE
Problem: creating a second stream for the same payee, overrides first stream

### ISSUE THREAD

**Issue by markholdex** [holdex/payment-streaming#61]
Solution: Smart contract should not allow to create another stream unless the previous one was terminated.

**Comment by zolotokrylin** [comment]
@markholdex Why not?

**Comment by zolotokrylin** [comment]
I think the problem is clear, but the solution limits the use cases. What if you need to have a second stream for the same developer?

**Comment by markholdex** [comment]
@zolotokrylin multiple streams not possible by default. And @accompany1205 proposed the shortest solution at the moment in order for the current fictionality to not break. Otherwise, we get stuck in long lasting PRs. 

We can think in V2 how can we support multiple streams.
