### ISSUE TITLE
Problem: solidity coverage packed is not integrated into github CI process

### ISSUE THREAD

**Issue by zolotokrylin** [holdex/payment-streaming#67]
Problem: solidity coverage packed is not integrated into github CI process

_Originally posted by @zolotokrylin in https://github.com/holdex/payment-streaming/issues/58#issuecomment-1635239240_

**Comment by CTAPCKPIM** [comment]
@zolotokrylin 

Correctly understood that I need to modify `test.yml`?

**Comment by zolotokrylin** [comment]
@CTAPCKPIM `test.yml` for sure, but probably also extend the package.json. I am not sure about the last one here

**Comment by CTAPCKPIM** [comment]
@zolotokrylin
Done
I propose to install a dependency so that the command `npm run coverage` does not display `MockUSDT.sol`

How here:
![image](https://github.com/holdex/payment-streaming/assets/83241890/497afad3-db8b-4fac-89be-9664594eecb1)
