### ISSUE TITLE
Problem: Payee can't claim USDT from previous stream because a new stream started

### ISSUE THREAD

**Issue by markholdex** [holdex/payment-streaming#69]
When first stream has terminated but Payee didn't claim, and the second stream already started, Payee will never be able to claim the USDT from their first stream.

**Comment by markholdex** [comment]
@accompany1205 what is your opinion about this problem?

**Comment by accompany1205** [comment]
@markholdex we fix this problem.
Before creating next stream, we can check the balance of previous stream using "accumulation" function.
If the balance of previous stream exists, payers shouldn't create next sream.
