### ISSUE TITLE
Problem: Payee can't claim unclaimed USDT after termination period

### ISSUE THREAD

**Issue by markholdex** [holdex/payment-streaming#70]
If Payee doesn't claim their USDT before termination period, there is a high chance to lose all USDT because smart contract doesn't allow to claim them anymore. What if the Payee forgets to claim or is too busy to claim now. He needs to have a possibility to still claim tokens after termination period except the amount that will be calculated, will only be until the termination period and not current timestamp.

**Comment by markholdex** [comment]
@accompany1205 what's your opinion about this problem. It just struck me that Payee could have a problem like this and there is not way to solve it.

**Comment by accompany1205** [comment]
@markholdex This has been implemented already.
Pleas have a look at this.
https://github.com/holdex/payment-streaming/blob/main/contracts/StreamManager.sol#L197-L201

**Comment by markholdex** [comment]
@accompany1205 my bad, you are right. this problem is also covered.
