### ISSUE TITLE
Problem: team members don't have access to Payer and Admin wallet addresses to test streaming

### ISSUE THREAD

**Issue by markholdex** [holdex/payment-streaming#79]
```[tasklist]
### Sub-problems
- [ ] https://github.com/holdex/payment-streaming/issues/77
- [ ] https://github.com/holdex/payment-streaming/issues/76
```

Proposed solution:

During deployment, we specify the admin and the payer address.

**Comment by markholdex** [comment]
That's fine for me too. Except there is no way to set a gnosis address until we solve the sub-problems.

**Comment by almon-s** [comment]
@markholdex the sub problems seem complete. Is there anything else needed here to close this one?

**Comment by zolotokrylin** [comment]
@markholdex how is the problem solved? how can I test things without asking people to pass me ownership?
