### ISSUE TITLE
Problem: payment stream is missing termination period

### ISSUE THREAD

**Issue by markholdex** [holdex/payment-streaming#8]
- When I create a payment stream
- I want to define a termination period
- So that the stream can't be cancelled immediately

When a Payer wants to work with a candidate, they also define a termination period. This period allows the stream to continue working after it has been cancelled, for X amount of time. 

Example: 
- block 0: stream was created with 10 blocks termination period
- block 5: Payer terminates stream
- block 8: Payee claims payment from block 0 to block 8
- block 15: Payee claim payment from block 8 to block 15
- block 17: Payee calls claim function, but fails with "stream was terminated" error

sub: #2

**Comment by accompany1205** [comment]
@markholdex Could you assign this issue to me?

**Comment by accompany1205** [comment]
@markholdex Who can terminate open streams? Admin or Payer?

**Comment by georgeciubotaru** [comment]
@accompany1205 The answer is in the description of the task
