### ISSUE TITLE
Problem: Accumulation function returns wrong value.

### ISSUE THREAD

**Issue by accompany1205** [holdex/payment-streaming#82]
`uint256 amount = calculate(_payee, block.timestamp);`
It passes `block.timestamp` as a claimed time, but if it's terminated, it should be `terminatedAt + terminationPeriod`

**Comment by zolotokrylin** [comment]
@accompany1205 
I think `uint256 amount = calculate(_payee, block.timestamp);` is correct.
Payee can claim only up to the time he is making a claim.

I don't follow why you are proposing `terminatedAt + terminationPeriod` as a time point. Please explain.

**Comment by accompany1205** [comment]
@zolotokrylin 
I mean by the case that the stream is terminated. After termination period, a payee can call this function to know its accumulated amount.

**Comment by accompany1205** [comment]
@zolotokrylin What do you think of?

**Comment by markholdex** [comment]
If the stream is terminated, then accumulation should return 0, because there is nothing more left for the Payee to claim. I believe I'm right. If the Payee hasn't claimed yet, then we should display how much is left to claim. I believe it's a different problem that we don't account for claimed amount in the accumulation.

**Comment by accompany1205** [comment]
```
function accumulation(address _payee) public view returns(uint256) {
        if (block.timestamp <= streamInstances[_payee].createdAt + streamInstances[_payee].cliffPeriod)
            return 0;

        uint256 amount = calculate(_payee, block.timestamp);
        //@dev return the amount
        return amount;
    }
    
    As you can see, it only checks if it's in cliff period. Are you okay with it?

**Comment by markholdex** [comment]
@accompany1205 what would be the value returned in this case if everything is already claimed? or if the block.timestamp is bigger than termination period end?

**Comment by accompany1205** [comment]
@markholdex 
If everything is already claimed, it should return 0
 if the block.timestamp is bigger than termination period end and claimable amount remains, it should return the claimable amounts.
 That's what I am just about to do.

**Comment by markholdex** [comment]
> if the block.timestamp is bigger than termination period end and claimable amount remains, it should return the claimable amounts.

@accompany1205 so it already works like that?

**Comment by accompany1205** [comment]
I am working on it
