### ISSUE TITLE
Problem: Daniil's PRs include old irrelevant commits

### ISSUE THREAD

**Issue by zolotokrylin** [holdex/payment-streaming#98]
> Problem: Daniil's PRs include old irrelevant commits

_Originally posted by @zolotokrylin in https://github.com/holdex/payment-streaming/issues/93#issuecomment-1652926001_

**Comment by zolotokrylin** [comment]
@CTAPCKPIM you need to resolve this issue.
Try to delete the repository and then clone it again.

Currently, all your PRs include very old commits. It is not clean.

**Comment by georgeciubotaru** [comment]
@CTAPCKPIM Also, please describe how you are creating new branches.

If it's okay for you to use CLI, no problems, but try to use the visual features from VSCode.

**Comment by CTAPCKPIM** [comment]
@georgeciubotaru 

> @CTAPCKPIM Also, please describe how you are creating new branches.

(console)
- `git checkout -b <name_new_branch>`
- `git add <file/s>`
...
- `git push origin <name_new_branch>` 

> If it's okay for you to use CLI, no problems, but try to use the visual features from VSCode.

did not quite understand this part (I use Soclime text 3)

**Comment by georgeciubotaru** [comment]
@CTAPCKPIM How about Github Desktop?

**Comment by CTAPCKPIM** [comment]
> @CTAPCKPIM How about Github Desktop?

Almost didn't use

P.S. Problem solved(pull #101)
![image](https://github.com/holdex/payment-streaming/assets/83241890/ff98aca1-7616-457a-9efb-1a4feeea118f)

**Comment by zolotokrylin** [comment]
@CTAPCKPIM how did you fix it, so we also know about it?

**Comment by CTAPCKPIM** [comment]
@zolotokrylin 
- Creating the **new folder**
- Inside the **new folder** `git clone <link>`
